/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "pronouns"
include(
    "pronouns-api",
    "pronouns-squirtgun",
    "pronouns-bukkit",
    "pronouns-bungee",
    "pronouns-discord",
    "pronouns-cloud-server"
)