/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "pronouns"
include(":pronouns-api")
include(":pronouns-squirtgun")
include(":pronouns-papi")
include(":pronouns-bukkit")
include(":pronouns-bungee")